### ISSUE TITLE
Black should remove unnecessary outer parentheses around function arguments

### ISSUE THREAD

**Issue by jdufresne** [python/black#548]
Operating system: **Fedora release 27**
Python version: **Python 3.6.6**
*Black* version: **18.9b0**
Does also happen on master: **Yes**

Input:

```py
print((1))
```

Expected change:

```py
print(1)
```

Actual: file left unchanged

**Comment by rooterkyberian** [comment]
`print(((1)))` will also be unchanged where we expected it to be equal to `print(1)`

Something that is likely another issue, but similar:
```
f = lambda a: (1)
g = lambda a: ((1))
```
will also be left unchanged

tested with 
Python version: Python 3.7.0
Black version: 18.9b0

**Comment by sr105** [comment]
Duplicate of #445

**Comment by JelleZijlstra** [comment]
Don't think this is quite a dupe.

**Comment by sr105** [comment]
Both involve black removing unnecessary tuple parentheses. The code to fix one will likely fix the other.
