### ISSUE TITLE
Inconsistency in formatting new line at the beginning of the code block

### ISSUE THREAD

**Issue by cypreess** [python/black#579]
Operating system: mac os Mojave
Python version: 3.6
*Black* version: 18.9b0
Does also happen on master: didn't test

Black will allow for such formatting at the same time:

```
def test_a():

    print("a")
    while 1:

        print("a")


def test_b():
    print("b")
    while 1:
        print("c")
```

I understand that preserving single empty line inside of the code block is allowed for visual code segmentation, however, I can't see how does this feature used for code block beginning helps for readability as it is just not consistent.

**Comment by ambv** [comment]
I agree and originally Black was stripping all that whitespace. This turned out to be an area of tremendous contention so currently it leaves vertical whitespace pretty much alone (unless you use more than one -- or two on module level -- blank lines).

This is not something we will be changing.
