### ISSUE TITLE
Collapsing new lines before on elif/else/except blocks?

### ISSUE THREAD

**Issue by ndevenish** [python/black#635]
I've found a whole lot of code in our project written in the style:
```python
if condition == "something":
    do_some_code()

elif condition == "else":
    do_something_else()

else:
    do_fallback()

try:
    do_more_things(condition)

except ValueError:
    respond_to_exception()
```
Which I've not encountered before, and makes it very hard to visually separate into blocks for reading. I'd expected black to reformat to:
```python
if condition == "something":
    do_some_code()
elif condition == "else":
    do_something_else()
else:
    do_fallback()

try:
    do_more_things(condition)
except ValueError:
    respond_to_exception()
```
But it isn't handled. Is this within black's scope?

(Colleague: "PEP8 doesn't tell you not to do this", which I guess is an argument, but I think technically PEP8 doesn't tell you to not to wrap one line simple if statements in brackets `if (condition):` either)

**Comment by ambv** [comment]
What you're asking for was the original behavior of Black. It met with *tremendous* amount of criticism so now Black will let you keep your vertical whitespace within functions (up to one empty line at a time). This is unfortunately not actionable.
