### ISSUE TITLE
Multiple equations badly formatted

### ISSUE THREAD

**Issue by hyperknot** [python/black#658]
**Black v18.9b0**

[Playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACwAFxdAD2IimZxl1N_WlOfrjrwTD_HmvgwnJjzRnP6n-xxfG5N8soIT3rQw7f-YAHVeE4KDeKJSCk_4NAb0AkxO1arg5CoR2IYzIc2l5s12VzSqetqyeFj_rWgNeNQ1kcAAHSxlALBjJkpAAF4sQEAAACwHT-xscRn-wIAAAAABFla)

## Options

`--line-length=60`

## Input

```python
a = b = c = d = e = None

a_variable = b_variable = c_variable = d_variable = e_variable = None

```

## Output

```python
a = b = c = d = e = None

a_variable = (
    b_variable
) = c_variable = d_variable = e_variable = None

```

## Expected
Anything else really, this doesn't make any sense like this.

**Comment by colecrtr** [comment]
How do you believe it should be formatted? It's only reformatting it like that to keep the same logic within your specified line length parameter, as far as I can tell this is expected behavior.

**Comment by JelleZijlstra** [comment]
The formatting Black produces isn't great, but I'm not sure how to do better. It would be consistent with other formatting choices in Black to put every variable on its own line, but that requires backslashes, which Black tries to avoid.

**Comment by hyperknot** [comment]
I'd normally prefer it to go over the character limit or solve it with
backslashes.

**Comment by hyperknot** [comment]
@colecrtr thanks that's good to know!

**Comment by ambv** [comment]
I believe this is one of the cases of [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out). There is no clear solution since the input is already rather unreadable semantically. I would advise minor refactoring, readers of your code will thank you.
