### ISSUE TITLE
Specify line length on the README.md examples

### ISSUE THREAD

**Issue by sponsfreixes** [python/black#677]
The default line length is 88, but for the examples on the section **How Black wraps lines** it seems to be lower. I was confused by this example:

```
# in:

TracebackException.from_exception(exc, limit, lookup_lines, capture_locals)

# out:

TracebackException.from_exception(
    exc, limit, lookup_lines, capture_locals
)
```

Because as it's 75 characters long, nothing should change. From the previous two paragraphs I figured out that it was intended to be longer than the line length, but it doesn't says what the line length is and it can be confusing.

**Comment by zsol** [comment]
Feel free to submit a pull request ;)

**Comment by sponsfreixes** [comment]
What's preferred?
- Option 1: Change the example so that it works with the default limit of 88 characters.
- Option 2: State that for illustrative purposes the line length of the example is 75 characters.

**Comment by JelleZijlstra** [comment]
Option 1 seems more consistent to me. We generally want to discourage nonstandard configuration options, including line length.
