### ISSUE TITLE
cosmetic alignment of inline comments (like yapf SPACES_BEFORE_COMMENT)

### ISSUE THREAD

**Issue by reagle** [python/black#682]
Operating system: MacOS Mojave
Python version: 3.7
*Black* version: 19.9b0
Does also happen on master: yes

I would like Black to maintain cosmetic spaces before comments to maintain column alignments. For example, in your [pytree.py](https://github.com/ambv/black/blob/master/blib2to3/pytree.py#L43) comments are nicely aligned, which Black would remove.

```
    # Default values for instance variables
    type = None    # int: token number (< 256) or symbol number (>= 256)
    parent = None  # Parent node pointer, or None
    children = ()  # Tuple of subnodes
    was_changed = False
    was_checked = False
```
Of course, this is old Guido code -- and I notice your code has virtually no inline comments. 

Is this functionality possible?

**Comment by ambv** [comment]
No, this is not planned.

**Comment by earonesty** [comment]
sad
