### ISSUE TITLE
Inconsistent spacing between import and expression

### ISSUE THREAD

**Issue by Delgan** [python/black#705]
Operating system: Windows
Python version: 3.6.4
*Black* version: v18.9b0
Does also happen on master: Probably (black.now.sh raises an error on master @250ba7)

---

Hi.

Spacing between `import` statements and first expression of the file add one or two lines, depending on the number of new lines before formatting.

Strangely, this does not happen if expression is a function declaration.

**Input `#1`**
```python
import sys
a = 1
```

**Output `#1`**
```python
import sys

a = 1
```

**Input `#2`**
```python
import sys



a = 1
```

**Output `#2`**
```python
import sys


a = 2
```

According to PEP 8, I think this should set two new lines all the time.

**Comment by ambv** [comment]
PEP 8 only says: "Surround top-level function and class definitions with two blank lines." What it should do between imports and other code is not explicitly worded. Black allows both single and double blank lines in this situation because there is no clarity on this.
