### ISSUE TITLE
black conflicts with flake8-docstrings aka pydocstyle

### ISSUE THREAD

**Issue by Midnighter** [python/black#709]
I've seen mention of this in https://github.com/ambv/black/issues/144#issuecomment-392650993 but did not spot an adequate solution. A blank line is introduced by black between a function docstring and a local function definition (which I personally agree with). However, this triggers D202 which complains about that line. I'm not sure what the official recommendation is. Any pointers?

**Comment by zsol** [comment]
I realize this is not a practical recommendation, but I think pep257 should be changed to allow a blank line after the docstring of a function in cases where the immediately following statement is an inner function declaration.

**Comment by ambv** [comment]
PEP 8 says: "Use blank lines in functions, sparingly, to indicate logical sections." An inner function **is** a logical section if I ever saw one. I agree with Zsolt that PEP 257 could relax its expectations here.

**Comment by Code0x58** [comment]
`flake8-docstrings` is a wrapper around `pydocstyle`, which has a PR to stop this from being a validation error https://github.com/PyCQA/pydocstyle/pull/395

**Comment by ccosby** [comment]
Adding this comment so that D202 shows up in GitHub Issue search.

**Comment by MuellerSeb** [comment]
https://github.com/PyCQA/pydocstyle/pull/426 fixes this.
Was released with https://github.com/PyCQA/pydocstyle/releases/tag/5.0.0
