### ISSUE TITLE
Add a __main__.py to allow for executable zip files

### ISSUE THREAD

**Issue by brettcannon** [python/black#713]
Looking at the dependencies that Black requires, they all seem to be pure Python (I believe aiohttp breaks that, but it's listed as an optional dependency). That would mean that if you constructed a zip file with a `__main__.py` at the top along with all dependencies included then you should be able to point Python at the zip and have Black work in a self-contained manner.

This was just an idea I had while people talk about packaging tools over at discuss.python.org.

**Comment by ambv** [comment]
Thanks for your feedback. This will stop being true once we compile with mypyc or introduce other performance measures that compile Black. We won't be moving to `__main__.py` for this reason (we don't want to break users in the future).
