### ISSUE TITLE
black fails on print function when using Python 2.7 as target version

### ISSUE THREAD

**Issue by Kami** [python/black#768]
When running black on Python file which uses ``from __future__ import print_function`` statement with Python 2.7 target, it fails with the following error:

```bash
$ black --target-version py27 test.py 
error: cannot format test.py: Cannot parse: 5:21: print("foo bar", file=sys.stderr)
All done! 💥 💔 💥
1 file failed to reformat.
$ cat test.py
from __future__ import print_function

import sys

print("foo bar", file=sys.stderr)
```

Since ``from __future__ import print_function`` statement is used, I don't think it should fail in this scenario.

## Environment information:

Operating system: Ubuntu Xenial
Python version: Python 3.6.7
*Black* version: black, version 19.3b0

**Comment by JelleZijlstra** [comment]
I believe this is fixed in master, can you check?

**Comment by runekaagaard** [comment]
It still seems not to work. After doing:

    sudo pip3 uninstall black
    sudo pip3 install git+git://github.com/ambv/black.git@cea13f498418784e22f8fbd78db3f9240a2bad11

Creating a `test.py` file with this:

    def foo(a    ):
        print 42

I get the following output:

    $ black -l 80 -t py27 test.py
    error: cannot format test.py: cannot use --safe with this file; failed to parse source file with Python 3.6's builtin AST. Re-run with --fast or stop using deprecated Python 2 syntax. AST error message: Missing parentheses in call to 'print'. Did you mean print(42)? (<unknown>, line 2)
    All done! 💥 💔 💥
    1 file failed to reformat.

**Comment by runekaagaard** [comment]
I tested it against cea13f498418784e22f8fbd78db3f9240a2bad11 and it works.

**Comment by chingc** [comment]
Will there be a new release soon that includes this fix?  I'm in the process of migrating a codebase to python 3 and would prefer not to disable black.

**Comment by chingc** [comment]
Nevermind, I was able to use the fixed version by updating my pre-commit config.  🎉

**Comment by jace** [comment]
I just ran into this problem using `pre-commit` with the `stable` branch. What release are you all using? Should I switch to `master`?

**Comment by truh** [comment]
I also just ran into this problem. This is my pyproject.toml

```
[tool.black]
target_version = ['py27', 'py36']
```

I use black version`19.3b0` which I just installed from pip.

**Comment by BrianChristie** [comment]
Also ran into this issue. Is there a new release planned soon?

**Comment by hugovk** [comment]
Yes, there'll be a new release out soonish, see https://github.com/psf/black/issues/988.
