### ISSUE TITLE
Can't copy out of input or output field

### ISSUE THREAD

**Issue by dms-cat** [python/black#791]
**Black https://github.com/ambv/black/commit/cea13f**

[Playground link](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADRAFVdAD2IimZxl1N_WkWHIqhiNwPVaq_UXHFBRXCwaz8BEPtMjcg3cU8cWqqN9SJ0dqhyJFRDlksfK-YT4-fmLRFjyDW4gxYVSq8hqdE-vxXIk4k99yGmPIcAAAAAcXJry5MYQ-4AAXHSAQAAAOVBokixxGf7AgAAAAAEWVo=)

## Options

`--line-length=60`

## Actual behaviour

I can't copy from the left or right text boxes, neither with the mouse or the keyboard copy buffer. Running Firefox 66.0.2 on Arch Linux.

**Comment by JelleZijlstra** [comment]
Could you report this to https://github.com/jpadilla/black-playground? This is not an issue with Black itself. (For what it's worth I can't reproduce it either, but I'm on a different browser and OS.)

**Comment by dms-cat** [comment]
For anyone wondering why there isn't a playground bug report, it looks like this has been fixed in the meantime.
