### ISSUE TITLE
No line breaks for long lines with unpacking

### ISSUE THREAD

**Issue by tweakimp** [python/black#827]
Operating system: Win10 64bit
Python version: 3.3
*Black* version: 19.3b0
Does also happen on master: yes
See [black playground](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AH_AK9dAD2IimZxl1OAqkiw1qdEZwTwAkF6QyPceS0UE3r0IfbZZWVAYQvF-VSYjfdP8t0qSKN-s1LatA0TDvvo6OKmOPhNqxLns9IZu_itufs1EWY3s5HmGOiC4loRx7rqP88sQwLX2iEOm8WXH4DGKNELWpupBVTe83fTAr1JqL0Cd517vE6T_AYvMkl0D1-9TxOpqRfuWT1JLqb0Mf-e65gRLFVp2VtYIt-E8r-_joZsDQAAAKjrUfPTJpNdAAHLAYAEAAD9DUpvscRn-wIAAAAABFla)

When there are many long names to the right side of an `=` sign, black stacks them vertically.
However, for many long names on the left side there is no solution and the line stays too long.

I dont know if this is intended or if there is no other way to solve this, but maybe you have a solution for me :)

**Comment by JelleZijlstra** [comment]
This is a bug, but it's already being tracked at #445. Thanks for your report!
