### ISSUE TITLE
Term "dedent" fix proposal

### ISSUE THREAD

**Issue by plaihonen** [python/black#831]
README file has 3 times the term `dedented`.
Proposal to fix them to read `unindented`

IMHO `dedent` has nothing to do with coding
[https://en.wiktionary.org/wiki/dedent](https://en.wiktionary.org/wiki/dedent)

**Comment by JelleZijlstra** [comment]
"Dedent" is a term used internally in the CPython implementation. But if "unindent" is clearer, we're happy to change the README. PRs welcome!

**Comment by hugovk** [comment]
> IMHO `dedent` has nothing to do with coding
> https://en.wiktionary.org/wiki/dedent

I think dedent is fine, especially for Python. That link's first definition is:

> (computing, transitive, primarily Python) To outdent.

Two of its three citations are from Python. 

Searching GitHub code and Python docs:

| Term | GitHub results | Python docs pages |
| - | - | - |
| unindent | 858,897 | 0 |
| dedent | 5,847,838 | 11 |
| outdent | 10,261,394 | 0 |

**Comment by plaihonen** [comment]
Interesting!
For some reason I completely missed the line which mentions the "especially for python".
Eventually I'll learn to understand the term "dedent".
