### ISSUE TITLE
Feature request: Allow only module-based imports

### ISSUE THREAD

**Issue by mitar** [python/black#841]
I would request that black also modifies imports so that it does not allow any importing of symbols, but just Python modules. So if somebody writes code like:

```python
from foo.bar import MyClass

MyClass()
```

It would be changed to:

```python
from foo import bar

bar.MyClass()
```

Or:

```python
from foo import MyClass

MyClass()
```

To:

```python
import foo

foo.MyClass()
```

**Comment by JelleZijlstra** [comment]
This is outside the scope of Black. Even if we did start doing AST-modifying changes, this is unlikely to be one of them. The change you're proposing would require us to analyze symbol tables to make sure the new variable name doesn't create conflicts. Also, I don't think there is general agreement that your proposed code style is better.

**Comment by mitar** [comment]
It is used in Google Python style: https://github.com/google/styleguide/blob/gh-pages/pyguide.md#22-imports

**Comment by JelleZijlstra** [comment]
But that style guide allows `from sound.effects import echo` where `echo` is a module. How is Black supposed to know whether `echo` here is a module imported from the `sound.effects` package, or a function imported from the `sound.effects` module?

**Comment by mitar** [comment]
I would probably answer static analysis and you would answer that this is out of scope of Black? :-)
