### ISSUE TITLE
Documentation request: best way to setup a blackd client tool?

### ISSUE THREAD

**Issue by sirosen** [python/black#854]
I tried to finally get setup with blackd running as a systemd user unit, and I'm not clear from the docs how I should be setting up the client side of this.

<details><summary>I'm able to setup a working unit with this config</summary>

```
$ cat ~/.config/systemd/user/blackd.service
[Unit]
Description=blackd autoformatting server
[Service]  # installed in a virtualenv
ExecStart=/home/sirosen/bin/blackd-env/bin/blackd --bind-port 9090
[Install]
WantedBy=default.target
```
</details>

<details><summary>and then test this with simple curl</summary>

```
$ curl -sf -XPOST localhost:9090 -d "$(cat setup.py)" > /dev/null; echo $?
0
```
</details>

So it works, hooray!

I wanted to start using this in pre-commit hooks and other places.

I almost asked "how do I setup `black` to call out to `blackd`?" but that obviously defeats the whole point of blackd. How are people doing this? Is there some standard client tool in use?

I think even a doc note that "you need to write your own blackd client" is fine, just to alleviate any confusion about this.

**Comment by zsol** [comment]
Indeed there's no blackd client in this repo yet, but there are some plans to write one.  Until then, maybe it's better to write a sentence about this in the docs as you point out. Happy to accept a PR about this :)
