### ISSUE TITLE
Black should use the line length suggested by PEP8 by default and optionally provide a config parameter to overwrite.

### ISSUE THREAD

**Issue by venthur** [python/black#855]
Black should use the line length suggested by PEP8 by default and optionally provide a config parameter to overwrite.

While I understand and agree that you can do whatever you want in your project, It would probably benefit the project if the defaults sticks as closely as possible to the thing that it wants to fix (i.e. making PEP8 compliant code) -- but with an option to change it to other values.

**Comment by zsol** [comment]
Black implements a subset of PEP8, not all of it. Specifically, the default line length of 88 is explained in [the readme](https://github.com/python/black#line-length) and is unlikely to change at this point.

**Comment by venthur** [comment]
Sure thing, it's your project so you can decide whatever you want. On the other hand, PEP8 is not going away anytime soon, so just wondering why you make everyone elses's live a bit harder to enforce *your* preferred style. I'd be nice to have an uncompromising re-formatter w/o options. You realized yourself that this one option will be debated and added an option for a different line length already.

Hopefully you'll change your mind on that sometime. Otherwise, good work with `black`, it is better than the alternatives already.
