### ISSUE TITLE
INTERNAL ERROR: Black produced invalid code: invalid syntax / f-string expression part cannot include a backslash

### ISSUE THREAD

**Issue by kprzybyla** [python/black#863]
Operating system: ArcoLinux (Arch)
Python version: 3.7.3
*Black* version: 19.3b0
Does also happen on master: Yes, but the error is different

Minimal example code:
```python
x = f'{y * " "} \'{z}\''
```

On *Black* @ 19.3b0:

> error: cannot format test.py: INTERNAL ERROR: Black produced invalid code: f-string expression part cannot include a backslash (<unknown>, line 1). Please report a bug on https://github.com/ambv/black/issues.  This invalid output might be helpful: /tmp/blk_z08rm6fp.log

```python
  File "/home/krprzyby/.local/lib/python3.7/site-packages/black.py", line 3388, in assert_equivalent
    dst_ast = ast.parse(dst)
  File "/usr/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
```

On *Black* @ master:

> error: cannot format /home/krprzyby/test.py: INTERNAL ERROR: Black produced invalid code: invalid syntax (<unknown>, line 1). Please report a bug on https://github.com/python/black/issues.  This invalid output might be helpful: /tmp/blk_ygw12on1.log

```python
  File "/home/krprzyby/b/black/black.py", line 3502, in assert_equivalent
    dst_ast = parse_ast(dst)
  File "/home/krprzyby/b/black/black.py", line 3443, in parse_ast
    return ast27.parse(src)
  File "/home/krprzyby/b/venv/lib/python3.7/site-packages/typed_ast/ast27.py", line 50, in parse
    return _ast27.parse(source, filename, mode)
x = f"{y * \" \"} '{z}'"
```

Looks like on version 19.3b0 code is not formatted because *Black* recognizes that it would be formatted into code with invalid syntax, on master however code is formatted but then when *Black* checks if code has proper syntax, an error is raised.

**Comment by zsol** [comment]
I can repro this, it'll be fixed before the next release
