### ISSUE TITLE
INTERNAL ERROR: Black produced code that is not equivalent to the source

### ISSUE THREAD

**Issue by Carreau** [python/black#877]
Minimal example below.

Operating system: macos
Python version: 3.7.1 / 3.6.7 
*Black* version: 19.3b0 
Does also happen on master: Yes 7ce3894f23adf94f2f3cf206e06e7dce9f4ce401 (May 26)

```
def f():
# fmt: off
    pass

def b():
    pass
```

Log file: 
<details>
<pre>
--- src
+++ dst
@@ -13,38 +13,38 @@
             None,  # NoneType
         )  # /arguments
       body=
         Pass(
         )  # /Pass
+        FunctionDef(
+          args=
+            arguments(
+              args=
+              defaults=
+              kw_defaults=
+              kwarg=
+                None,  # NoneType
+              kwonlyargs=
+              vararg=
+                None,  # NoneType
+            )  # /arguments
+          body=
+            Pass(
+            )  # /Pass
+          decorator_list=
+          name=
+            'b',  # str
+          returns=
+            None,  # NoneType
+          type_comment=
+            None,  # NoneType
+        )  # /FunctionDef
       decorator_list=
       name=
         'f',  # str
       returns=
         None,  # NoneType
       type_comment=
         None,  # NoneType
     )  # /FunctionDef
-    FunctionDef(
-      args=
-        arguments(
-          args=
-          defaults=
-          kw_defaults=
-          kwarg=
-            None,  # NoneType
-          kwonlyargs=
-          vararg=
-            None,  # NoneType
-        )  # /arguments
-      body=
-        Pass(
-        )  # /Pass
-      decorator_list=
-      name=
-        'b',  # str
-      returns=
-        None,  # NoneType
-      type_comment=
-        None,  # NoneType
-    )  # /FunctionDef
   type_ignores=
 )  # /Module
</pre>
</details>

I can't reproduce that on `black.now.sh` ... and well the + and - in the logs appear to be identical... utf-8 encoded and no special invisible chars according to vim.

**Comment by illfated** [comment]
MarkDown Tip: you can use **```diff** as the top code block fence line if you want to see diff syntax highlighting.

**Comment by Carreau** [comment]
Well ... No because it's in a detail HTML tag, and you can't use markdown
in them (at least it did not let me), so I have a HTML-pre for formatting.

**Comment by zsol** [comment]
This is what happens on master. Looks like the same problem as #884 
```diff
--- bug.py      2019-06-15 08:34:18.051142 +0000
+++ bug.py      2019-06-15 08:34:50.965094 +0000
@@ -1,7 +1,7 @@
 def f():
-# fmt: off
+    # fmt: off
     pass
 
-def b():
-    pass
+    def b():
+        pass
```
