### ISSUE TITLE
Black collapses multiple expressions with trailing comments

### ISSUE THREAD

**Issue by joaoe** [python/black#881]
Operating system: Windows 10
Python version: Python 3.6
*Black* version: 19.3b0
Does also happen on master: yes

Code
```
x = [
	1,  # x=1
	2,  # x=2
	3,  # x=3
]

x = {
	1: 1,  # x=1
	2: 2,  # x=2
	3: 3,  # x=3
}

func(
	1,  # x=1
	2,  # x=2
	3,  # x=3
)
```
becomes
```
x = [1, 2, 3]  # x=1  # x=2  # x=3

x = {1: 1, 2: 2, 3: 3}  # x=1  # x=2  # x=3

func(1, 2, 3)  # x=1  # x=2  # x=3
```

Collapsing the lines would be OK if there were not comments, but the comments are there to give context to each value, so because the comments are merged, that context is broken.

Would be nice if Black did not move comments around and if it needs to keep a line split to maintain the comment in the same line, then it should. Even though comments are not part of the AST, Black should definitely not move comments around.

**Comment by zsol** [comment]
This is the same as #800
