### ISSUE TITLE
unreadable function/method definition after reflow by black

### ISSUE THREAD

**Issue by jberends** [python/black#882]
### Operating system:
* Python version: 3.6
* *Black* version: ==19.3b0
* Does also happen on master: True

on version 19.3b
```python3
class Foo(object):
    def get_cludes(
        self, includes: List[str] = None, excludes: List[str] = None
    ) -> List[str]:
        pass
```
on master
```python3
class Foo(object):
    def get_cludes(
        self,
        includes: List[str] = None,
        excludes: List[str] = None,
    ) -> List[str]:
        pass
```
IMHO this is not really readable and this is borderline highly discussable in terms op opinionation:tm:.  This due to the fact that the code structure is visually 'cluttered' by the fact that the indent of the `def` is used instead of the underlying 'new' indent by the function/method. We in our office like consistent flow of code however this visually impairs really the clarity that PEP8 is advocating. Through your eyelids you want to see a block indent to determine the structure. Especially when using CodeGlance/Sublime.

```
oooo OooOoo(ooo):
    ooo oooo_oooooo(ooo  oooooo  ooooooo  ooooo oooooo):
        ooooo ooooooooooooooo ooooo ooooooooo oooo oooo
        ooooooooo oooo oooooooooooooooooooooooooooo
        oooooooooooooooooooooo ooooooo oooooooo ooooo
        oooooooooooo oooooooo ooooooooo oooo
```
I would suggest to reflow like so:
```python3
class Foo(object):
    def get_cludes(
            self, includes: List[str] = None, excludes: List[str] = None
        ) -> List[str]:
        pass
```

I have watched the screencast of Pycon and understand the mechanics of the reflow of code. Therefore unsure if this type of criticism is acceoted in this project or not, but just wanted to vent it anyway.

**Comment by JelleZijlstra** [comment]
Thanks for bringing this up, but this is a fundamental aspect of Black's style and we're unlikely to change it at this point. Many people are already relying on Black for production codebases and few of them have complained about the style decision you've highlighted here.
