### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by mlucool** [python/black#883]
Hi,

I have a bug that seems to be fixed in master, is there a release planned soon?

The bug is this that fails to be parsed when target is py27:
```
from __future__ import print_function
# ...
print(line, file=sout)
```

Thanks!

**Comment by illfated** [comment]
(see also #517)

**Comment by mlucool** [comment]
FTR, I don't mind a prerelease

**Comment by waynew** [comment]
If you're just looking to get it locally you can run 

```
python3.7 -m pip install --user -U --pre git+https://github.com/python/black.git
```

(or whatever python you're using)

**Comment by drunkwcodes** [comment]
@mlucool How about nightly rollout?

**Comment by mlucool** [comment]
I'd rather use a formal release as its not just for me, but for a larger group. It's harder to align people to a version without some sort of tag (I could just choose a commit, but again that's ugly). Plus, it's nice to have something checkpointed and semi-blessed as a good state as the thing we install.

A nightly build is better than a commit, but not as good as a person declaring this is in a good state, here is a new tag.

**Comment by drunkwcodes** [comment]
@mlucool What happened after you claimed that the bug is fixed in `master` in your group?

**Comment by mlucool** [comment]
We ended up installing from a specific commit. Closing this as it seems that this request is not going to push anything forward.
