### ISSUE TITLE
unclear error with lambda

### ISSUE THREAD

**Issue by pascaldelange** [python/black#888]
Hi,

The following code causes an error with black when run on my computer
Operating system: MacOS
Python version: code is 2.7, but black runs on 3.7
*Black* version: 19.3b0
Does also happen on master: yes

`beam.Map(lambda (k, bundle): bundle)`

The same seems to work with the online formatter even though it is using the same version as me (also passes on master)

Is this a known issue ?

**Comment by pascaldelange** [comment]
P.S.
The error is 
`error: cannot format /Users/pascal/Documents/shine/dataflow/pipelines/dataflow_tools/dataflow_tools.py: cannot use --safe with this file; failed to parse source file with Python 3.7's builtin AST. Re-run with --fast or stop using deprecated Python 2 syntax. AST error message: invalid syntax (<unknown>, line 308)`

**Comment by JelleZijlstra** [comment]
Sounds like you may have misconfigured the `--target-version` option. Make sure it includes 2.7.

**Comment by pascaldelange** [comment]
I think I have it configured properly. Here is my pyproject.toml:
`[tool.black]
line-length = 88
target_version = ['py27']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs
    | \*.egg-info
    | \.git  
...
  )/
)
'''
`

**Comment by zsol** [comment]
I can't reproduce this @pascaldelange no matter the `--target-version` I give *Black*. Can you provide steps to repro, please?
