### ISSUE TITLE
Extra white space in slicing

### ISSUE THREAD

**Issue by marcelotrevisani** [python/black#889]
Operating system: Ubuntu 18.10
Python version: 3.7.3
*Black* version: 19.3b0
Does also happen on master: Yes

I was using black and I saw that ``flake8`` is complaining about one correction which ``black`` did.
For example:
```python
foo_a = [1, 2, 3]
foo_b = [4, 5, 6]

foo_c = [7, 8, 9, 10, 11, 12, 13]

foo_list = foo_c[foo_a[1]:foo_b[2]]
```

According to ``PEP8``, this code is correct (If I am wrong please point me where I can find an explanation for it). However, ``black`` formatted it to:
```python
foo_a = [1, 2, 3]
foo_b = [4, 5, 6]

foo_c = [7, 8, 9, 10, 11, 12, 13]

foo_list = foo_c[foo_a[1] : foo_b[2]]
```
with extra empty spaces in the slicing operation.

**Comment by hugovk** [comment]
This is by design, please see: https://github.com/python/black#slices

**Comment by marcelotrevisani** [comment]
Ok then! Because I was thinking that this case was slightly different. But thanks for your answer. I am going to close it then.

**Comment by SicariusNoctis** [comment]
I can't see anything about this particular case in PEP8.

Also, this:

```python
img[:shape[0], :shape[1]]
```

looks a bit better than:

```python
img[: shape[0], : shape[1]]
```
