### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by knakad** [python/black#901]
Hi there!
Looks like black is having trouble with this bit of code.
See details linked below:

Operating system: Reproducible on Windows and Ubuntu
Python version: 3.6.8
*Black* version: black==19.3b0
Does it also happen on master: Yes

Output:
`$ black -l 100 ./
error: cannot format C:\Users\knakad\workspace\SageMakerPythonSDK\src\sagemakerpythonsdk\src\sagemaker\rl\estimator.py
: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/ambv/black/issues.  This diff might be helpful: C:\Users\knakad\AppData\Local\Temp\blk_epnkfdbs.log
All done! � � �
223 files left unchanged, 1 file failed to reformat.`

[blk_epnkfdbs.log](https://github.com/python/black/files/3316212/blk_epnkfdbs.log)

**Comment by knakad** [comment]
FYI, no rush on this issue. I fixed the underlying problem.
I wanted to report it in case others run into it and are unable to resolve the underlying problem.

**Comment by zsol** [comment]
Are you sure this is still broken on master? #872 is supposed to fix this kind of issue

**Comment by zsol** [comment]
I can't repro on master. If you still can, feel free to reopen with an example that fails.
