### ISSUE TITLE
Black stuck on bad cache(?)

### ISSUE THREAD

**Issue by dimaqq** [python/black#903]
After running `black` from Python3.8 virtualenv, I am unable to run `black` from Python3.7 virtualenv on the same codebase, even on completely new files:

```
> black x.py
error: cannot format x.py: unsupported pickle protocol: 5
All done! 💥 💔 💥
1 file failed to reformat.
```

Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: macOS
Python version: 3.8b + 3.7
*Black* version: 19.3b0
Does also happen on master: dunno

**Comment by dimaqq** [comment]
Probably duplicate of #875

**Comment by dimaqq** [comment]
TL;DR, on Mac, do `rm -rf ~/Library/Caches/black/*`

**Comment by zsol** [comment]
Yes, let's keep the discussion in #875

**Comment by adam505hq** [comment]
On linux: `rm -rf ~/.cache/black/*`

**Comment by Marco-Sulla** [comment]
On windows, the dir is located in C:\Users\USERNAME\AppData\Local\black\black\Cache
