### ISSUE TITLE
Using Black with Xonsh

### ISSUE THREAD

**Issue by meatballs** [python/black#904]
I'd like to use Black to format [xonsh](https://github.com/xonsh/xonsh) scripts, but, of course, any non-Python lines in those scripts fail to parse.

I've tried adding # fmt: on/off statements, but they don't appear to affect the parsing.

Is there a way to mark lines or blocks to be completely ignored by Black for parsing as well as formatting?

**Comment by zsol** [comment]
Not really. You'll need to separate out the Python parts yourself and pass them on to Black for formatting

**Comment by meatballs** [comment]
Ah well, it was worth a try. Thanks for the response.
