### ISSUE TITLE
Exceeding line limit for tuple returning funcitons

### ISSUE THREAD

**Issue by jim-pansn** [python/black#905]
Operating system: macOS 10.14.1
Python version: Python 3.6.8 :: Anaconda, Inc.
*Black* version: black, version 19.3b0
Does also happen on master: yes

If you have a function that returns a tuple of values and you want to assign it to multiple variables by implicitly unpacking the tuple. And because of long variable names this spans more characters than the given line length, black cannot shorten the line.
If you add parenthesis around the tuple of assigned variables black can split it up to several lines in order to respect line length. 

Before black 
```
very_long_variable_name, another_super_long_variable_name = function_that_returns_tuple_and_also_has_a_long_name(arg)

(very_long_variable_name, another_super_long_variable_name) function_that_returns_tuple_and_also_has_a_long_name(arg)
```
After black
```
very_long_variable_name, another_super_long_variable_name = function_that_returns_tuple_and_also_has_a_long_name(
    arg
)

(
    very_long_variable_name,
    another_super_long_variable_name,
) = function_that_returns_tuple_and_also_has_a_long_name(
    arg
)

```
Link to minimal example in online formatter: https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AE8AJJdAD2IimZxl1N_Wmp_J_tu2Yxt5S2uR7Vve9f5yNEzzTShB_RstUNPmU_J9Nvz3Qkul2N4B-AjEmRyCsIUz9R8b6VgT6VEuF_pbleFnHGNniiYj6lKk1JvF0IX8qwYDUIm3EMmmZssj4srsuNRfh6QMD9Aq0y5Pje-iPZmkKIa5-26jRgR_hRbIh0fCP_D_gJzjGutAAAAgFSXLTOOr7cAAa4BvQIAANrPvzGxxGf7AgAAAAAEWVo=

**Comment by JelleZijlstra** [comment]
I believe this is fixed in master, can you check?

**Comment by zsol** [comment]
it is indeed
