### ISSUE TITLE
Black refuses to format modules named build

### ISSUE THREAD

**Issue by alefnula** [python/black#923]
Operating system: MacOSX
Python version: 3.6
*Black* version: 19.3b0
Does also happen on master: Haven't tested.

This is a really strange thing. Black refuses to format a project that is named `build`.

```bash
$ black --check build
No paths given. Nothing to do 😴

$ mv build bbb

$ black --check bbb
would reformat [...].py
would reformat [...].py
would reformat [...].py
would reformat [...].py
would reformat [...].py
All done! 💥 💔 💥
5 files would be reformatted, 6 files would be left unchanged.
```

Am I doing something wrong or this is a bug?

**Comment by lroellin** [comment]
Note the `--check` option only returns if changes WOULD be made (I use it in a linter script):
https://black.readthedocs.io/en/stable/installation_and_usage.html#command-line-options

>   --check                        
Don't write the files back, just return the
                                  status.  Return code 0 means nothing would
                                  change.  Return code 1 means some files
                                  would be reformatted.  Return code 123 means
                                  there was an internal error.

**Comment by lroellin** [comment]
Seems like 'build' is one of the default excludes: https://github.com/python/black/blob/f3bb22a828495c66d8d2dae1edf45e15fc2daddb/black.py#L55

As a workaround, maybe you can include it with `--include build`?

**Comment by alefnula** [comment]
OK, tnx! It's just weird unexpected behaviour :)

**Comment by zsol** [comment]
I see why this is surprising, but the harm caused is hopefully less than accidentally formatting build artifacts in a `build/` directory.

We won't be changing the default excludes for now.
